// <auto-generated />
using System;
using AdBanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdBanner.Data.Migrations
{
    [DbContext(typeof(AdBannerContext))]
    [Migration("20221029142146_FetchSumarry")]
    partial class FetchSumarry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdBanner.Data.Model.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("AdBanner.Data.Model.BannerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<int>("FKBanner")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKBanner");

                    b.ToTable("BannerStats");
                });

            modelBuilder.Entity("AdBanner.Data.Model.BannerStatsSummary", b =>
                {
                    b.Property<int>("ClickPerHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ImpressionPerHour")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BannerStatsSummaries");

                    b
                        .HasAnnotation("Relational:SqlQuery", "select a.Id, a.Title, b.Hour,CONVERT(date, b.Date) [Date], (Select COUNT(*) from BannerStats where FKBanner = a.Id and Hour = b.Hour and Event = 2) as ClickSummary,\r\n                (Select COUNT(*) from BannerStats where FKBanner = a.Id and Hour = b.Hour and Event = 1) as ImpressionSummary  \r\n                from Banners a cross join BannerStats b group by hour,a.Id,Title, CONVERT(date, b.Date) order by Hour");
                });

            modelBuilder.Entity("AdBanner.Data.Model.BannerStat", b =>
                {
                    b.HasOne("AdBanner.Data.Model.Banner", "Banner")
                        .WithMany("BannerStats")
                        .HasForeignKey("FKBanner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banner");
                });

            modelBuilder.Entity("AdBanner.Data.Model.Banner", b =>
                {
                    b.Navigation("BannerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
